v2.0.0

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,21 @@
 #!/bin/bash
-# wget -O - https://raw.githubusercontent.com/Tasshack/dreame-vacuum/dev/install | bash -
+# Install latest version:
+# wget -O - https://raw.githubusercontent.com/Tasshack/dreame-vacuum/master/install | bash -
+# Install specific version:
+# wget -O - https://raw.githubusercontent.com/Tasshack/dreame-vacuum/master/install | bash -s -- v2.0.0
 set -e
+
+if [ -z "$1" ]; then
+    echo "Fetching latest version..."
+    VERSION=$(wget -qO- https://api.github.com/repos/Tasshack/dreame-vacuum/releases | grep -m 1 '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
+    if [ -z "$VERSION" ]; then
+        echo "Failed to fetch the latest version."
+        exit 1
+    fi
+else
+    VERSION="$1"
+fi
+
 
 declare path
 declare -a paths=(
@@ -27,7 +42,7 @@ if [ -n "$path" ]; then
         mkdir "$path/custom_components"
     fi
     cd "$path/custom_components"
-    wget "https://github.com/Tasshack/dreame-vacuum/releases/download/v2.0.0b25/dreame_vacuum.zip"
+    wget "https://github.com/Tasshack/dreame-vacuum/releases/download/$VERSION/dreame_vacuum.zip"
     if [ -d "$path/custom_components/dreame_vacuum" ]; then
         rm -R "$path/custom_components/dreame_vacuum"
     fi
